- id: '1681063929166'
  alias: Living Room Scene Controller
  description: ''
  use_blueprint:
    path: Matt-PMCT/ZoozZen32forZwaveJs.yaml
    input:
      zooz_switch: 435f1c698c163ea2ab2049cce787f972
      scene_5:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.living_room
      scene_1:
      - service: fan.toggle
        data: {}
        target:
          entity_id: fan.living_room
      scene_2:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.kitchen
      scene_3:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.kitchen_corner
      scene_4:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.dining
- id: '1681086854576'
  alias: Office Ring Keypad
  description: ''
  use_blueprint:
    path: ImSorryButWho/synchronize-ring-alarm-keypad-v2-with-alarmo.yaml
    input:
      keypad: 577ddd2eaab3147f70955d9915828327
      alarm: alarm_control_panel.secure_home
- id: '1681086901296'
  alias: Bedroom Ring Keypad
  description: ''
  use_blueprint:
    path: ImSorryButWho/synchronize-ring-alarm-keypad-v2-with-alarmo.yaml
    input:
      keypad: 577ddd2eaab3147f70955d9915828327
      alarm: alarm_control_panel.secure_home
- id: '1681086923351'
  alias: Master Bedroom Ring Keypad
  description: ''
  use_blueprint:
    path: ImSorryButWho/synchronize-ring-alarm-keypad-v2-with-alarmo.yaml
    input:
      keypad: 9497830c0d5f3fcce6a652b64a836af6
      alarm: alarm_control_panel.secure_home
- id: '1681192839272'
  alias: Kitchen Scene Controller
  description: ''
  use_blueprint:
    path: Matt-PMCT/ZoozZen32forZwaveJs.yaml
    input:
      zooz_switch: c775e997039e11dd46241821d8bad75e
      scene_5: []
      scene_1:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.kitchen
      scene_2:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.dining
      scene_3:
      - service: light.toggle
        data: {}
        target:
          entity_id: light.living_room
      scene_4:
      - service: fan.toggle
        data: {}
        target:
          entity_id: fan.living_room
