input_boolean:

  back_lanai_auto:
    name: Back Lanai Automation
    initial: on
    icon: mdi:home-automation

mqtt:
  switch:
    - command_topic: "shellyplus1-a8032abc2b68/rpc"
      name: "Living Room 2"
      unique_id: "shellyplus1-a8032abc2b68-switch-0"
      payload_on: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 0, "on": true}}'
      payload_off: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 0, "on": false}}'
      state_topic: "shellyplus1-a8032abc2b68/status/switch:0"
      value_template: "{{ value_json.output }}"
      state_on: true
      state_off: false
      qos: 1

    - command_topic: "shellyplus1-a8032abb4b0c/rpc"
      name: "Garage 1"
      unique_id: "shellyplus1-a8032abb4b0c-switch-0"
      payload_on: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 0, "on": true}}'
      payload_off: '{"id": 1, "src":"homeassistant", "method": "Switch.Set", "params": {"id": 0, "on": false}}'
      state_topic: "shellyplus1-a8032abb4b0c/status/switch:0"
      value_template: "{{ value_json.output }}"
      state_on: true
      state_off: false
      qos: 1

    - command_topic: "shellies/shellyswitch25-E8DB84A27568/relay/0/command"
      name: Living Room 3
      unique_id: "shellyswitch25-E8DB84A27568-switch-0"
      payload_on: "on"
      payload_off: "off"
      qos: 1
      state_topic: "shellies/shellyswitch25-E8DB84A27568/relay/0"
      json_attributes_topic: "shellies/shellyswitch25-E8DB84A27568/info"

automation:
  - alias: Back Lanai Fan Switch 1
    trigger:
      - platform: state
        entity_id: switch.back_lanai_1
        to:
    action:
      - service: fan.toggle
        entity_id: fan.back_lanai

  - alias: Back Lanai Light Switches
    trigger:
      - platform: state
        entity_id: switch.living_room_3
        to:
      - platform: state
        entity_id: switch.garage_1
        to:
    action:
      - service: light.toggle
        entity_id: light.back_lanai

  - alias: Back Lanai Motion
    trigger:
      - platform: state
        entity_id: binary_sensor.back_lanai_pir
        to: "on"
    condition:
      - condition: numeric_state
        entity_id: sensor.back_lanai_illuminance
        below: 7
      - condition: state
        entity_id: input_boolean.back_lanai_auto
        state: "on"
    action:
      - service: light.turn_on
        entity_id: light.back_lanai

  - alias: Back Lanai No Motion
    trigger:
      - platform: state
        entity_id: binary_sensor.back_lanai_occupancy
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.back_lanai_auto
        state: "on"
    action:
      - service: light.turn_off
        entity_id: light.back_lanai
