automation:

  - alias: Turn Christmas Tree Lights Off At Sunrise When People Away
    description: ''
    trigger:
      - platform: sun
        # Possible values: sunset, sunrise
        event: sunrise
    condition:
      condition: state
      entity_id:
        - group.people
      state: "not_home"
    action:
    - type: turn_off
      device_id: 90cb8e2816b2a1565702d289160cc582
      entity_id: light.dining_outlet
      domain: light
    mode: single

  - alias: Turn Christmas Tree Lights On at Sunset
    description: ''
    trigger:
      - platform: sun
        # Possible values: sunset, sunrise
        event: sunset
    condition: []
    action:
      - type: turn_on
        device_id: 90cb8e2816b2a1565702d289160cc582
        entity_id: light.dining_outlet
        domain: light
    mode: single

  - alias: Christmas Tree Lights On When People Home During Day
    trigger:
      - platform: state
        entity_id:
          - group.people
        from: "not_home"
        to: "home"
    condition:
      - condition: sun
        after: sunrise
        before: sunset
    action:
      - service: light.turn_on
        entity_id: light.dining_outlet

  - alias: Christmas Tree Lights On When People Away During Day
    trigger:
      - platform: state
        entity_id:
          - group.people
        from: "home"
        to: "not_home"
    condition:
      - condition: sun
        after: sunrise
        before: sunset
    action:
      - service: light.turn_off
        entity_id: light.dining_outlet
