input_boolean:

  dining_room_auto:
    name: Dining Room Automation
    initial: on
    icon: mdi:home-automation

automation:

  - alias: Dining Room Auto Off
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.main_occupancy
        from: "on"
        to: "off"
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.dining_room_auto
          state: "on"
    action:
      - service: light.turn_off
        entity_id:
          - light.dining
