input_boolean:
  kitchen_auto:
    name: Kitchen Automation
    initial: on
    icon: mdi:home-automation

group:
  kitchen_sink_cabinet_flood:
    name: Kitchen Sink Cabinet Flood
    entities:
      - binary_sensor.kitchen_sink_cabinet_1_flood
      - binary_sensor.kitchen_sink_cabinet_2_flood

automation:
  # - alias: Kitchen 0H Motion
  #   trigger:
  #     - platform: state
  #       entity_id:
  #         - binary_sensor.kitchen_occupancy
  #       from: "off"
  #       to: "on"
  #   condition:
  #     condition: and
  #     conditions:
  #       - condition: state
  #         entity_id: binary_sensor.kitchen_occupancy
  #         state: "on"
  #       - condition: time
  #         after: "23:59:59"
  #         before: "01:00:00"
  #       - condition: state
  #         entity_id: input_boolean.kitchen_auto
  #         state: "on"
  #   action:
  #     - service: light.turn_on
  #       data:
  #         transition: 15
  #         entity_id: light.kitchen_corner
  #         brightness: 1

  # - alias: Kitchen 1H Motion
  #   trigger:
  #     - platform: state
  #       entity_id:
  #         - binary_sensor.kitchen_occupancy
  #       from: "off"
  #       to: "on"
  #   condition:
  #     condition: and
  #     conditions:
  #       - condition: time
  #         after: "00:59:59"
  #         before: "02:00:00"
  #       - condition: state
  #         entity_id: input_boolean.kitchen_auto
  #         state: "on"
  #   action:
  #     - service: light.turn_on
  #       data:
  #         entity_id: light.kitchen_corner
  #         brightness: 1

  # - alias: Kitchen 2H-5H Motion
  #   trigger:
  #     - platform: state
  #       entity_id:
  #         - binary_sensor.kitchen_occupancy
  #       from: "off"
  #       to: "on"
  #   condition:
  #     condition: and
  #     conditions:
  #       - condition: numeric_state
  #         entity_id: sensor.kitchen_illuminance
  #         below: 5
  #       - condition: time
  #         after: "01:59:59"
  #         before: "05:00:00"
  #       - condition: state
  #         entity_id: input_boolean.kitchen_auto
  #         state: "on"
  #   action:
  #     - service: light.turn_on
  #       data:
  #         transition: 15
  #         entity_id: light.kitchen_corner
  #         brightness: 1

  # - alias: Kitchen 5H Motion
  #   trigger:
  #     - platform: state
  #       entity_id:
  #         - binary_sensor.kitchen_occupancy
  #       from: "off"
  #       to: "on"
  #   condition:
  #     condition: and
  #     conditions:
  #       - condition: numeric_state
  #         entity_id: sensor.kitchen_illuminance
  #         below: 5
  #       - condition: time
  #         after: "04:59:59"
  #         before: "06:00:00"
  #       - condition: state
  #         entity_id: input_boolean.kitchen_auto
  #         state: "on"
  #   action:
  #     - service: light.turn_on
  #       data:
  #         transition: 15
  #         entity_id: light.kitchen_corner
  #         brightness: 50

  - alias: Kitchen 6H-20H Motion
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.kitchen_pir
        from: "off"
        to: "on"
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id:
            - sensor.kitchen_illuminance
          below: 10
        - condition: time
          after: "06:00:00"
          before: "20:00:00"
        - condition: state
          entity_id: input_boolean.kitchen_auto
          state: "on"
    action:
      - service: light.turn_on
        entity_id: light.kitchen
      # - service: light.turn_on
      #   data:
      #     transition: 15
      #     entity_id: light.kitchen_corner
      #     brightness: 255

  # - alias: Kitchen 20H Motion
  #   trigger:
  #     - platform: state
  #       entity_id:
  #         - binary_sensor.kitchen_occupancy
  #       from: "off"
  #       to: "on"
  #   condition:
  #     condition: and
  #     conditions:
  #       - condition: time
  #         after: "19:59:59"
  #         before: "21:00:00"
  #       - condition: state
  #         entity_id: input_boolean.kitchen_auto
  #         state: "on"
  #   action:
  #     - service: light.turn_on
  #       entity_id: light.kitchen
  #     - service: light.turn_on
  #       data:
  #         transition: 15
  #         entity_id: light.kitchen_corner
  #         brightness: 225

  # - alias: Kitchen 21H Motion
  #   trigger:
  #     - platform: state
  #       entity_id:
  #         - binary_sensor.kitchen_occupancy
  #       from: "off"
  #       to: "on"
  #   condition:
  #     condition: and
  #     conditions:
  #       - condition: time
  #         after: "20:59:59"
  #         before: "22:00:00"
  #       - condition: state
  #         entity_id: input_boolean.kitchen_auto
  #         state: "on"
  #   action:
  #     - service: light.turn_on
  #       data:
  #         transition: 15
  #         entity_id: light.kitchen_corner
  #         brightness: 175

  # - alias: Kitchen 22H Motion
  #   trigger:
  #     - platform: state
  #       entity_id:
  #         - binary_sensor.kitchen_occupancy
  #       from: "off"
  #       to: "on"
  #   condition:
  #     condition: and
  #     conditions:
  #       - condition: time
  #         after: "21:59:59"
  #         before: "23:00:00"
  #       - condition: state
  #         entity_id: input_boolean.kitchen_auto
  #         state: "on"
  #   action:
  #     - service: light.turn_on
  #       data:
  #         transition: 15
  #         entity_id: light.kitchen_corner
  #         brightness: 100

  # - alias: Kitchen 23H Motion
  #   trigger:
  #     - platform: state
  #       entity_id:
  #         - binary_sensor.kitchen_occupancy
  #       from: "off"
  #       to: "on"
  #   condition:
  #     condition: and
  #     conditions:
  #       - condition: time
  #         after: "22:59:59"
  #         before: "00:00:00"
  #       - condition: state
  #         entity_id: input_boolean.kitchen_auto
  #         state: "on"
  #   action:
  #     - service: light.turn_on
  #       data:
  #         transition: 15
  #         entity_id: light.kitchen_corner
  #         brightness: 75

  - alias: Kitchen Auto Off
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.kitchen_occupancy
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.kitchen_auto
        state: "on"
    action:
      - service: light.turn_off
        entity_id:
          - light.kitchen
          - light.kitchen_corner

  - alias: Turn Kitchen Sink Flood Alert on after Kitchen Sink Flood Cleared
    trigger:
      - platform: state
        entity_id: group.kitchen_sink_cabinet_flood
    action:
      - service: alert.turn_on
        target:
          entity_id: alert.kitchen_sink_cabinet_flood

  - alias: "Telegram callback to stop alerts for kitchen sink"
    trigger:
      - platform: event
        event_type: telegram_callback
        event_data:
          data: "/kitchen_sink_acknowledge"
    action:
      - service: alert.turn_off
        target:
          entity_id: alert.kitchen_sink_cabinet_flood

  - alias: Kitchen Button Short Press
    trigger:
      - device_id: 17326fa900dd700c2a47b354f5da7e84
        domain: zha
        platform: device
        type: remote_button_short_press
        subtype: remote_button_short_press
    action:
      - service: light.toggle
        entity_id: light.kitchen

  - alias: Kitchen Button Double Press
    trigger:
      - device_id: 17326fa900dd700c2a47b354f5da7e84
        domain: zha
        platform: device
        type: remote_button_double_press
        subtype: remote_button_double_press
    action:
      - service: light.turn_on
        entity_id:
          - light.kitchen
          - light.kitchen_corner

  - alias: Kitchen Button Long Press
    trigger:
      - device_id: 17326fa900dd700c2a47b354f5da7e84
        domain: zha
        platform: device
        type: remote_button_long_release
        subtype: remote_button_long_release
    action:
      - service: light.turn_off
        entity_id:
          - light.kitchen
          - light.kitchen_corner

alert:
  kitchen_sink_cabinet_flood:
    name: Kitchen Sink Cabinet Flood
    message: "💧 Kitchen Sink Cabinet Flood Detected"
    done_message: "👌 Kitchen Sink Cabinet Flood Cleared"
    entity_id: group.kitchen_sink_cabinet_flood
    state: "on"
    repeat:
      - 5
    can_acknowledge: true
    skip_first: false
    data:
      inline_keyboard:
        - "Acknowledge:/kitchen_sink_acknowledge"
    notifiers:
      - telegram
