input_boolean:
  living_room_auto:
    name: Living Room Automation
    initial: on
    icon: mdi:home-automation

group:
  main_sensors:
    name: Main Occupancy
    entities:
      - binary_sensor.side_entrance_occupancy
      - binary_sensor.front_entrance_occupancy
      - binary_sensor.kitchen_occupancy
      - binary_sensor.living_room_occupancy

mqtt:
  switch:
    - command_topic: "shellies/shellyswitch25-E8DB84AB4931/relay/0/command"
      name: Side Entrance 1
      unique_id: "side_entrance_1"
      payload_on: "on"
      payload_off: "off"
      qos: 1
      state_topic: "shellies/shellyswitch25-E8DB84A24B67/relay/0"
      json_attributes_topic: "shellies/shellyswitch25-E8DB84A24B67/info"
    - command_topic: "shellies/shellyswitch25-E8DB84A24B67/relay/1/command"
      name: Side Entrance 2
      unique_id: "side_entrance_2"
      payload_on: "on"
      payload_off: "off"
      qos: 1
      state_topic: "shellies/shellyswitch25-E8DB84A24B67/relay/1"
      json_attributes_topic: "shellies/shellyswitch25-E8DB84A24B67/info"

light:
  - platform: group
    name: "Living Room"
    entities:
      - light.living_room_bulb_1
      - light.living_room_bulb_2

# input_select:
#   sofa_light_effect:
#     name: Sofa Light Effect
#     options:
#       - Fireplace
#       - Storm
#       - Rainbow
#       - Aura
#       - Police
#       - No Effect
#     initial: "No Effect"

automation:
  - alias: Living Room Fan Switch
    trigger:
      - platform: state
        entity_id: light.side_entrance_1
        to:
      # - platform: state
      #   entity_id: switch.living_room_2
      #   to:
    action:
      - service: fan.toggle
        entity_id: fan.living_room

  - alias: Living Room Light Switches
    trigger:
      # - platform: state
      #   entity_id: switch.living_room_1
      #   to:
      - platform: state
        entity_id: light.side_entrance_2
        to:
    action:
      - service: light.toggle
        entity_id: light.living_room

  - alias: Living Room Fan Light On if Off
    trigger:
      # - platform: state
      #   entity_id: switch.living_room_1
      #   to:
      - platform: state
        entity_id: switch.side_entrance_2
        to:
      - device_id: 75e03167e6bce5f7145d049194208817
        domain: zha
        platform: device
        type: remote_button_short_press
        subtype: remote_button_short_press
    condition:
      condition: state
      entity_id: light.living_room_fan
      state: "off"
    action:
      - service: light.turn_on
        entity_id: light.living_room_fan

  - alias: Living Room Motion When Dark
    trigger:
      - platform: state
        entity_id:
          - group.main_sensors
        from: "off"
        to: "on"
    condition:
      condition: and
      conditions:
        - condition: numeric_state
          entity_id: sensor.living_room_illuminance
          below: 3
        - condition: state
          entity_id: binary_sensor.pea_tv
          state: "off"
        - condition: state
          entity_id: input_boolean.living_room_auto
          state: "on"
        # - condition: or
        #   conditions:
        #     - condition: state
        #       entity_id: person.sea3pea0
        #       state: "home"
        #     - condition: state
        #       entity_id: person.belka
        #       state: "home"
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.living_room_lamp

  - alias: Living Room Auto Off
    trigger:
      - platform: state
        entity_id:
          - group.main_sensors
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.living_room_auto
        state: "on"
      - condition: state
        entity_id: binary_sensor.pea_tv
        state: "off"
    action:
      - service: homeassistant.turn_off
        entity_id:
          - light.living_room
          - switch.living_room_lamp
      - service: media_player.turn_off
        entity_id: media_player.pea_tv

  - alias: Turn Living Room Lamp off when Pea TV On
    trigger:
      - platform: state
        entity_id: binary_sensor.pea_tv
        to: "on"
        from: "off"
    action:
      - service: switch.turn_off
        entity_id: switch.living_room_lamp

  - alias: Living Room Light Button Short Press
    trigger:
      - device_id: 75e03167e6bce5f7145d049194208817
        domain: zha
        platform: device
        type: remote_button_short_press
        subtype: remote_button_short_press
    action:
      - service: light.toggle
        entity_id: light.living_room

  - alias: Living Room Light Button Double Press
    trigger:
      - device_id: 75e03167e6bce5f7145d049194208817
        domain: zha
        platform: device
        type: remote_button_double_press
        subtype: remote_button_double_press
    action:
      - service: light.turn_on
        entity_id:
          - light.living_room
        data:
          brightness_step: 30
          color_temp: 3500

  - alias: Living Room Light Button Long Press
    trigger:
      - device_id: 75e03167e6bce5f7145d049194208817
        domain: zha
        platform: device
        type: remote_button_long_release
        subtype: remote_button_long_release
    action:
      - service: light.turn_on
        entity_id:
          - light.living_room
        data:
          brightness_step: -30
          color_temp: 3500

  - alias: Living Room Fan Button Short Press
    trigger:
      - device_id: 6399f0b70230b9560f68268f3c956b59
        domain: zha
        platform: device
        type: remote_button_short_press
        subtype: remote_button_short_press
    action:
      - service: fan.toggle
        entity_id: fan.living_room

  - alias: Living Room Fan Button Double Press
    trigger:
      - device_id: 6399f0b70230b9560f68268f3c956b59
        domain: zha
        platform: device
        type: remote_button_double_press
        subtype: remote_button_double_press
    action:
      - service: fan.increase_speed
        target:
          entity_id: fan.living_room
        data:
          percentage_step: 33

  - alias: Living Room Fan Button Long Press
    trigger:
      - device_id: 6399f0b70230b9560f68268f3c956b59
        domain: zha
        platform: device
        type: remote_button_long_release
        subtype: remote_button_long_release
    action:
      - service: fan.decrease_speed
        target:
          entity_id: fan.living_room
        data:
          percentage_step: 33
