input_boolean:

  master_bedroom_auto:
    name: Master Bedroom Automation
    initial: on
    icon: mdi:home-automation

mqtt:
  switch:

    - command_topic: shellies/shellyswitch25-E8DB84A260FE/relay/0/command
      name: Master Bedroom 1
      payload_on: "on"
      payload_off: "off"
      qos: 1
      state_topic: shellies/shellyswitch25-E8DB84A260FE/relay/0
    - command_topic: shellies/shellyswitch25-E8DB84A260FE/relay/1/command
      name: Master Bedroom 2
      payload_on: "on"
      payload_off: "off"
      qos: 1
      state_topic: shellies/shellyswitch25-E8DB84A260FE/relay/1

automation:
  - alias: Master Fan Switch
    trigger:
      - platform: state
        entity_id: switch.master_bedroom_1
        to:
    action:
      - service: fan.toggle
        entity_id: fan.master_bedroom

  - alias: Master Light Switch
    trigger:
      - platform: state
        entity_id: switch.master_bedroom_2
        to:
    action:
      - service: light.toggle
        entity_id: light.master_bedroom

  - alias: Master Bedroom Auto Off
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.master_bedroom_occupancy
        from: "off"
        to: "on"
        for:
          minutes: 90
    condition:
      - condition: state
        entity_id: input_boolean.master_bedroom_auto
        state: "on"
    action:
      - service: light.turn_off
        entity_id: light.master_bedroom
