input_boolean:
  master_bedroom_auto:
    name: Master Bedroom Automation
    initial: on
    icon: mdi:home-automation

automation:
  - alias: master bedroom dimmer 1 --> 2
    description: ""
    trigger:
      - platform: state
        entity_id: light.master_bedroom_dimmer
    # condition:
    #   - condition: template
    #     value_template: >
    #       {{ not is_state_attr('light.master_bedroom_dimmer', 'brightness',
    #       states.light.bedroom_bulb.attributes.brightness ) }}
    action:
      - choose:
          - conditions:
              - condition: state
                entity_id: light.master_bedroom_dimmer
                state: "off"
            sequence:
              - service: light.turn_off
                target:
                  entity_id: light.master_bedroom
          - conditions:
              - condition: state
                entity_id: light.master_bedroom_dimmer
                state: "on"
            sequence:
              - service: light.turn_on
                target:
                  entity_id: light.master_bedroom
                # data:
                #   brightness: "{{ trigger.to_state.attributes.brightness }}"
        default: []
    mode: single

  - alias: Master Bedroom Fan High
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: 54:ef:44:10:00:4b:76:80
          command: 41_single
    condition: []
    action:
      - choose:
          - conditions:
              or:
                - condition: state
                  entity_id: fan.master_bedroom
                  state: "off"
                - condition: template
                  value_template: "{{ state_attr('fan.master_bedroom', 'percentage') != 100 }}"
            sequence:
              - service: fan.set_percentage
                data:
                  percentage: 100
                target:
                  entity_id: fan.master_bedroom
          - conditions:
              - condition: state
                entity_id: fan.master_bedroom
                state: "on"
              - condition: template
                value_template: "{{ state_attr('fan.master_bedroom', 'percentage') == 100 }}"
            sequence:
              - service: fan.turn_off
                target:
                  entity_id: fan.master_bedroom
    mode: single

  - alias: Master Bedroom Fan Medium
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_ieee: 54:ef:44:10:00:4b:76:80
          command: 42_single
    condition: []
    action:
      - choose:
          - conditions:
              or:
                - condition: state
                  entity_id: fan.master_bedroom
                  state: "off"
                - condition: template
                  value_template: "{{ state_attr('fan.master_bedroom', 'percentage') != 66 }}"
            sequence:
              - service: fan.set_percentage
                data:
                  percentage: 66
                target:
                  entity_id: fan.master_bedroom
          - conditions:
              - condition: state
                entity_id: fan.master_bedroom
                state: "on"
              - condition: template
                value_template: "{{ state_attr('fan.master_bedroom', 'percentage') == 66 }}"
            sequence:
              - service: fan.turn_off
                target:
                  entity_id: fan.master_bedroom
    mode: single

  # - alias: Master Fan Switch
  #   trigger:
  #     - platform: state
  #       entity_id: switch.master_bedroom_1
  #       to:
  #   action:
  #     - service: fan.toggle
  #       entity_id: fan.master_bedroom

  # - alias: Master Light Switch
  #   trigger:
  #     - platform: state
  #       entity_id: switch.master_bedroom_2
  #       to:
  #   action:
  #     - service: light.toggle
  #       entity_id: light.master_bedroom

  - alias: Master Bedroom Auto Off
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.master_bedroom_occupancy
        from: "off"
        to: "on"
        for:
          minutes: 90
    condition:
      - condition: state
        entity_id: input_boolean.master_bedroom_auto
        state: "on"
    action:
      - service: light.turn_off
        entity_id: light.master_bedroom
