input_boolean:

  side_entrance_auto:
    name: Side Entrance Automation
    initial: on
    icon: mdi:home-automation

automation:

- alias: Side Entrance Auto On
  trigger:
    - platform: state
      entity_id: binary_sensor.side_entrance_pir
      from: "off"
      to: "on"
  condition:
    - condition: numeric_state
      entity_id: sensor.side_entrance_illuminance
      below: 15
    - condition: state
      entity_id: input_boolean.side_entrance_auto
      state: "on"
  action:
    - service: light.turn_on
      entity_id: light.side_entrance

- alias: Side Entrance Auto Off
  trigger:
    - platform: state
      entity_id: binary_sensor.side_entrance_occupancy
      from: "on"
      to: "off"
  condition:
    - condition: state
      entity_id: input_boolean.side_entrance_auto
      state: "on"
  action:
    - service: light.turn_off
      entity_id: light.side_entrance
